[supabase]
SUPABASE_URL = "https://qvdvjhswflefoqzsrqrc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2ZHZqaHN3ZmxlZm9xenNycXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3MTU3MTUsImV4cCI6MjEwNTI5MTcxNX0.AjpCFdIcs-QyhPq3ByJVdtpbUp58sAl6SUlZa9UIVpQ"
